version: '3.8'

services:
  db:
    image: mysql:8
    container_name: wp-db
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  wordpress:
    depends_on:
      - db
    image: wordpress:apache
    container_name: wp
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html:rw
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
